apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: auth-service
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - image: docker.io/lmctague/auth-service:fc3e6d31a20d7d966c03285b91b09675dc84a1b7
        name: auth-service
        ports:
        - name: http
          containerPort: 80
        #livenessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        #readinessProbe:
        #  httpGet:
        #    path: "/"
        #    port: http
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: pg-database
              key: pg-database
        - name: PASSWORD_SECRET_KEY
          value: ""
        - name: JWT_SECRET_KEY
          value: ""
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"